### ISSUE TITLE
Is it possible to hide the initial utterance?

### ISSUE THREAD

**Issue by longhornrumble** [aws-samples/aws-lex-web-ui#731]
I do want the utterance because I want my intent to pick it up. I just don't want it to be visible in the chat window.  If it's possible, what command do I add to the config file. Thanks.

**Comment by israelias** [comment]
@longhornrumble Hey, yes it is. I think for your setup it might be as easy as:

`custom-chatbot-style.css`
```css
/* Hide the first human input message aka/dependent on initialUtterance */
.message-human:nth-of-type(1) {
    display: none !important;
}
```

Referencing this in case you want to trigger the intent on every startsession or reset action (in case those are enabled): https://github.com/aws-samples/aws-lex-web-ui/issues/197 the logic is there although the snippets don't reflect what's in the current release.
